platform :ios, '11.0'
target 'ChartboostMediationDemo' do

  use_frameworks!

  pod 'ChartboostMediationSDK', '~> 4.0'
# Uncomment any of the following lines to use provider
#  pod 'ChartboostMediationAdapterAdColony'
#  *** Remember to add your GADApplicationIdentifier to Info.plist if you use AdMob ***
#  pod 'ChartboostMediationAdapterAdMob'
#  pod 'ChartboostMediationAdapterAppLovin'
#  pod 'ChartboostMediationAdapterAmazonPublisherServices'
  pod 'ChartboostMediationAdapterChartboost'
#  pod 'ChartboostMediationAdapterDigitalTurbineExchange'
#  pod 'ChartboostMediationAdapterGoogleBidding'
#  pod 'ChartboostMediationAdapterInMobi'
#  pod 'ChartboostMediationAdapterIronSource'
#  pod 'ChartboostMediationAdapterMetaAudienceNetwork'
#  pod 'ChartboostMediationAdapterMintegral'
#  pod 'ChartboostMediationAdapterPangle'
#  pod 'ChartboostMediationAdapterTapjoy'
#  pod 'ChartboostMediationAdapterUnityAds'
#  pod 'ChartboostMediationAdapterVungle'
#  pod 'ChartboostMediationAdapterYahoo'

end

# Temporary CocoaPods fix for Xcode 15. CocoaPods merged the fix already, but haven't
# released it yet: https://github.com/CocoaPods/CocoaPods/pull/12009
# See discussion here: https://github.com/CocoaPods/CocoaPods/issues/12012
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
    end
end
